Algoritmo "Antecessor"
// Lógica de programação
// Professor: Jailson 
// Descrição   : Solicita um número e exibe seu antecessor
// Autor(a)    : Jean Carlos
// Data atual  : 24/01/2022
Var
// Seção de Declarações das variáveis 
numero1:inteiro
antecessor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Digite um número: ")
Leia(numero1)
antecessor<- numero1-1
Escreva("O antecessor do número",numero1," é ", antecessor)

Fimalgoritmo